### ISSUE TITLE
ClassNotFoundException: processing.sound.SoundFile when trying to play .wav file

### ISSUE THREAD

**Issue by OfekGiv** [processing/processing-sound#19]
I'm having an issue running this simple code as it says: 
ClassNotFoundException: processing.sound.SoundFile

import processing.sound.*;
SoundFile file;

void setup(){
  size(800,800);
  background(255);
  
  file = new SoundFile  (this,"BuzzerEffect.wav");
  file.play();
}
void draw(){
}

I'm using Processing 3.4 on Windows 10

**Comment by kevinstadler** [comment]
Is it possible that you don't have the Sound library installed? It isn't by default, but you can do so very easily using Processing's built-in Contribution Manager, just search for "Sound".

**Comment by OfekGiv** [comment]
I have the Sound library installed. I tried using the Minim library (after installing it from the Contribution Manager) and I get the same error.

**Comment by lulxiao** [comment]
Has anyone figured out the problem? I'm struggling with the same one.

**Comment by ziqqur4t** [comment]
I was able to reproduce it on Processing 4.3 (running on Win11)
When importing (installing) a library to Processing there is a directory created separately from the installation folder usually in "My documents" folder, which in my case was connected to OneDrive. 
Changing the directory in the Preferences in the Processing to another folder, and reinstalling the library solved this error.
