### ISSUE TITLE
Can't play sound files

### ISSUE THREAD

**Issue by ghost** [processing/processing-sound#25]
every time I try to play an mp3 sound file in processing I get the following error

INFO: Pure Java JSyn from www.softsynth.com, rate = 44100, RT, V16.8.0 (build 463, 2017-10-16)
ArrayIndexOutOfBoundsException: 3

when I try .wav files I get the following error

Sound library error: unable to decode sound file hopping.wav

here's the relevant code:

import processing.sound.*;
SoundFile file;
void setup() {

  file=new SoundFile(this,"hopping.wav");
  file.play();
}

I double checked, the files are in the sketch's data directory.

I've tried on my desktop Mac and my laptop running windows.  Same error on both.

**Comment by kevinstadler** [comment]
I think your file might be in 8-bit unsigned format which is currently not supported by the sound library, if you convert it to any other WAV encoding it should play (see #15)
