### ISSUE TITLE
Error when playing a sound in Processing, help!

### ISSUE THREAD

**Issue by BRosa99** [processing/processing-sound#27]
![image](https://user-images.githubusercontent.com/48721972/54611260-e61fd700-4a56-11e9-84d6-db9477468a62.png)

I am doing a uni project with Processing. However, when wanting to play a sound file, I keep getting this error. Does anyone know how to fix this?
Kind regards,
Rosa

**Comment by kevinstadler** [comment]
I think you just need to add a draw() method (even if it's an empty one). There is actually no error in your code, the sketch just stops running immediately because there is no draw() method to run.
Please let me know if that fixes your problem!

**Comment by BRosa99** [comment]
Thanks for the quick response! However, I already have a draw method (sorry, was not visible on the screenshot), so that cannot be the problem... When I delete the sound related commands, my program works fine. So it is really the soundFile that causes problems I think

**Comment by kevinstadler** [comment]
Is anything about the sketch actually broken, or is it just that you can't hear the sound file? Despite what it looks like, the red text in the console is not actually an error, it's just a status message by the sound library.

**Comment by BRosa99** [comment]
Ah thanks! I fixed it, the problem was the sound file itsself, not the programming code... Do you by any chance know how you can play a sound file for just on second and that it then stops?

**Comment by kevinstadler** [comment]
There is no built-in function for having it stop after one second, you'll probably have to store the time when you invoke `file.play()` (probably using Processing's `millis()` function), then check in `draw()` how much time has elapsed since and then call `file.stop()` if it's been more than a second.
