### ISSUE TITLE
Some MP3 files are played back with chirping

### ISSUE THREAD

**Issue by MLanghof** [processing/processing-sound#33]
If I play back the following file as `SoundFile` (after unzipping of course) I get unacceptable chirping:

[chirp.zip](https://github.com/processing/processing-sound/files/3169097/chirp.zip)

It's a low bitrate file that uses variable bitrate encoding and the bit reservoir feature of the MP3 standard (storing encoded data in preceding frames if those had space left). The chirping is exclusive to the `sound` library, e.g. Windows Media Player or VLC do not have it.

On the other hand, this file plays back without any audible chirping:

[noChirp.zip](https://github.com/processing/processing-sound/files/3169093/noChirp.zip)

This one also uses variable bitrates and bit reserviors.

Here are two more files (constant bitrate but using bit reservoirs) that have chirping: 

[moreChirp.zip](https://github.com/processing/processing-sound/files/3169100/moreChirp.zip)

I have been unable to find an MP3 file that uses constant bitrate, no reservoirs and has chirping (made harder by being unable to open most of my files) but I could not nail it down on any one aspect of the MP3 headers. Maybe it's just coincidence that those always worked. Maybe the issue is also related to #32 as the decoding process itself seems to be fragile already, although I don't really see how that would be possible.

**Comment by kevinstadler** [comment]
This is an issue of our MP3 decoder dependency that will probably not get fixed. Since MP3 is a proprietary format and licensing is an issue for open source projects we generally don't recommend using it. For maximum compatibility we suggest storing your audio files as a raw WAV instead.
