### ISSUE TITLE
Add filter resonance option

### ISSUE THREAD

**Issue by stuible** [processing/processing-sound#46]
Adding the ability to modify the resonance of the lowpass, highness and bandpass filters would be a great addition to the library.  Is there any plan to do so?  I've noticed this functionality is already available with p5: https://p5js.org/reference/#/p5.Filter

**Comment by kevinstadler** [comment]
I think what the p5 sound library refers to as "resonance" can already be controlled through the `bw` (bandwidth) parameter? https://processing.org/reference/libraries/sound/BandPass_bw_.html

That parameter is only available for the `BandPassFilter` obviously, but with the underlying JSyn sound synthesis library it would also be possible to allow Processing users to control the resonance of any filter by providing direct control to the different filters' `Q`. I'm not sure if "resonance" would be the correct method name for this, or if it should just be "Q"?
