### ISSUE TITLE
Does not work on Raspberry PI 4

### ISSUE THREAD

**Issue by theseanzo** [processing/processing-sound#49]
On the latest release of Raspbian, you cannot load files without them being inaudible. It causes crashes in programs I have run in previous raspbian versions.

**Comment by kevinstadler** [comment]
Thanks for reporting, could you post the error/stack trace that you get when trying to run your old sketches?

**Comment by monkstone** [comment]
@kevinstadler quite possibly this is due to a missing dependency, I had same issue. But then I installed pulseaudio and library worked.
```bash
sudo apt-get install pulseaudio
# and because it wont harm, might be useful later
sudo apt-get gstreamer1.0-pulseaudio
```

**Comment by monkstone** [comment]
Interestingly works out of box on ManjaroARM(64bit) OS on RaspberryPI4 where pulseaudio is already installed. People at Raspbian seem to have a hate thing going with pulseaudio.

**Comment by theseanzo** [comment]
Hey, just got back to PI development. Yeah, there isn't an error thrown. What happens is the audio constantly clips. I'm using raspbian 5.4.73-v7. I have pulseaudio installed and gstremmer1.0-pulseaudio.

**Comment by kevinstadler** [comment]
@theseanzo your original issue was about loading sound files, is the clipping issue also just with sound files or any kind of output audio? Could you try one of the simple oscillator examples and see if it has anything to do with output amplitude?
