### ISSUE TITLE
Version 1.3.1 not visible in the Processing Contribution Manager

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing-sound#50]
In the Contribution Manager version 1.3 is still shown. However when I delete an install again from the contribution manager I get the new version 1.3.1 indeed.

So or the update notification of the CM is not working (I know it has some issues), or something else is wrong.

**Comment by REAS** [comment]
The contributions list isn't automated, it's triggered through an interface. I'm running it right now.

**Comment by REAS** [comment]
OK, the list is updated, but it's not showing up. Maybe the data files for the contribution haven't been updated? This is for @wirsing

**Comment by REAS** [comment]
It's in the file on the server and looks fine from @wirsing https://processing.org/contrib_generate/contribs.txt

**Comment by REAS** [comment]
This is frustrating. I removed 1.3, then when I restarted Processing, it has the Sound library grayed out. It claims that I have 1.3.1 installed, but I see this:

![screen shot 2015-09-29 at 11 17 44 am](https://cloud.githubusercontent.com/assets/677774/10173924/c33efa60-669b-11e5-8268-bc4d0b23f6b2.png)

**Comment by REAS** [comment]
The file that @wirsing created looks correct, but the `maxRevision` in the `contribs.txt` is showing up as 228 as well. I'm posting an issue in processing/processing-docs about it.

name = Sound
authorList = The Processing Foundation
url = http://processing.org/reference/libraries/sound/index.html
category = Sound
sentence = Sound library for Processing.
paragraph =  
version = 6
prettyVersion = 1.3.1
minRevision = 228
maxRevision = 0

**Comment by REAS** [comment]
OK, finished up. The Sound library was in the list of broken libraries, but now it's out.
