### ISSUE TITLE
Support for Ogg Vorbis

### ISSUE THREAD

**Issue by Ectalite** [processing/processing-sound#53]
Hi I saw that your library was not working with .ogg sound files. So I wanted to know if there was a chance you would support Ogg/vorbis compression.

**Comment by kevinstadler** [comment]
Going to have another look at this using some extra dependencies (cf. https://odoepner.wordpress.com/2013/07/19/play-mp3-or-ogg-using-javax-sound-sampled-mp3spi-vorbisspi/, also https://mvnrepository.com/artifact/javazoom/jlayer)

**Comment by Ectalite** [comment]
Thanks a lot !
