### ISSUE TITLE
No Sound on Linux

### ISSUE THREAD

**Issue by sesselastronaut** [processing/processing-sound#59]
I've just installed the sound library via the library installer. Trying to run the SimplePlayback or SineWave example doesn't result in any sound coming from the speakers. Due to my research this has been experienced before as described in this forum: https://forum.processing.org/two/discussion/23402/using-processing-on-ubuntu-sound-library-runs-makes-no-sound. I've tried to produce sound with the Minim library as discussed there and it works fine. This is on processing 3.5.4 and the lates Sound library running Debian 10.04. Any hints very welcome, happy to provide more infos if of help.

**Comment by kevinstadler** [comment]
My hunch is that it's just a (output channel) configuration issue, can you check the text output of the following sketch to see what sound devices are recognized by the library:
```
import processing.sound.*;

void setup() {
  Sound.list();
}
```

By default the sound library will output to the first device in the list. If that is not the correct one, you can select the desired device at the beginning of any sound sketch using this method: https://processing.org/reference/libraries/sound/Sound_outputDevice_.html

Let me know if this solves your problem!

**Comment by sesselastronaut** [comment]
Many thanks, that was the fly in the ointment! Problem/issue solved!
