### ISSUE TITLE
[Solved] Audio glitches on Arch Linux

### ISSUE THREAD

**Issue by samuelebonaffino** [processing/processing-sound#60]
Hi, 

I've used this amazing library for quite a lot now, without any serious issues. Recently I installed Arch Linux on a Lenovo Miix 320 and everything works fine, including audio in every other program I run. Unfortunately, when I try to run any track or examples from your library, audio is completely glitched. My code runs fine and everything works, just you can't hear the audio properly at all. 
I'd like to mention I had other distros on this tiny laptop and I've never had this trouble before, also I don't see any notable loads on the CPU so it's not the case. I use ALSA + Pulseaudio and pavucontrol, I tried to uninstall and reinstall everything and it still doesn't work. Another thing I'd like to mention is that if I switch from speakers to headphones you can hear the glitchy audio through the correct source, so it recognises it and I guess the problem is not related to it. 

I have the latest version of Processing (3.5.4) and tried both the latest stable release and the v2.3.0 test build version of the library.

If you need any additional information ask me everything, I'm willing to help to solve the problem.

**Comment by kevinstadler** [comment]
Thanks for the thorough report. Have you ever tried playing sound from any other Java applications? The synthesis engine underlying the Sound library makes use of the JavaSound interface, and a quick google shows that this might be an issue with Java/JavaSound on Arch Linux generally, and not specifically Processing/the Sound library.

Another way to test this: could you try installing the `minim` Processing library and see if their example sketches also produce the same sound artefacts?

**Comment by samuelebonaffino** [comment]
Thanks a lot for answering back. I'll make all of the test you mentioned and let you know the results.

**Comment by samuelebonaffino** [comment]
Can't explain how happy I am to tell you it's now working. All I did was installing the additional package **pulseaudio-alsa**, and after a reboot this did the trick, you can find out more at this link: https://www.reddit.com/r/linux4noobs/comments/8qgcxy/java_sound_does_not_work_with_other_applications/
 
Also, just for the records, before finding this fix, I tried some examples from **Minim** library  and they didn't work as expected, so the problem is related to JavaSound/Pulseaudio/ALSA. Thank you so much for the hint, I'm so happy.

**Comment by kevinstadler** [comment]
That's great to hear, glad it's working now!
