### ISSUE TITLE
CoreAudio HookInit

### ISSUE THREAD

**Issue by nonlineari** [processing/processing-sound#62]
Hi, 

the issue is way ahead of my coreaudio knowledge.

I received a statement on p5 console:: Core Dumps is disabled and I think is missing a driver for DSD.
I have ALAC cloned and my macbookpro is able to read DSD. repatch the core dump and find missing library?

**p5 3.3.6. sound library 2.2.3**

New_SHP_PlugIn is called 
New_SHP_PlugIn is kAudioHardwarePlugInTypeID
New_SHP_PlugIn call CoreAudioHookInit
CoreAudioHookInit start ...
newAudioDeviceCreateIOProcID test 1
CheckIfSupportShareBuffer DevID 0x62, DSDFlag ret 0x77686f3f
newAudioDeviceCreateIOProcID test 6 not support DSD
newAudioDeviceDestroyIOProcID test 1
CheckIfSupportShareBuffer DevID 0x62, DSDFlag ret 0x77686f3f
newAudioDeviceDestroyIOProcID test 5 not support DSD
newAudioDeviceCreateIOProcID test 1
CheckIfSupportShareBuffer DevID 0x51, DSDFlag ret 0x77686f3f
newAudioDeviceCreateIOProcID test 6 not support DSD
newAudioDeviceStart test 1
CheckIfSupportShareBuffer DevID 0x51, DSDFlag ret 0x77686f3f
newAudioDeviceStart test 6 not support DSD
newAudioDeviceCreateIOProcID test 1
CheckIfSupportShareBuffer DevID 0x62, DSDFlag ret 0x77686f3f
newAudioDeviceCreateIOProcID test 6 not support DSD
newAudioDeviceStart test 1
CheckIfSupportShareBuffer DevID 0x62, DSDFlag ret 0x77686f3f
newAudioDeviceStart test 6 not support DSD

**Comment by kevinstadler** [comment]
This is the repository for the (Java) Processing Sound library, for `p5.js` and `p5.sound` issues please open a ticket over at https://github.com/processing/p5.js/issues
