### ISSUE TITLE
Disabling caching doesn't work as stated in documentation

### ISSUE THREAD

**Issue by OpenSauce04** [processing/processing-sound#63]
![image](https://user-images.githubusercontent.com/48618519/109821355-cb3bd280-7c2d-11eb-900a-9e4583954281.png)
![image](https://user-images.githubusercontent.com/48618519/109821416-ddb60c00-7c2d-11eb-9e35-244381886a18.png)
![image](https://user-images.githubusercontent.com/48618519/109821389-d5f66780-7c2d-11eb-93a6-ac2ed0436795.png)
What am I doing wrong here?

**Comment by kevinstadler** [comment]
The Sound library version which adds the `cache` argument (version 2.3.0) was only released yesterday, so the update might not have propagated to the Processing Library Manager yet.

Solutions/workarounds:
* if your sketch only loads a couple of sound files then you don't have to worry about caching, just leave out the last parameter
* if you need to disable caching now, you can download the zip of the new release from here and extract the library into your `Processing/libraries/sound` folder: https://github.com/processing/processing-sound/releases/tag/v2.3.0
* version 2.3.0 of the library should become available for automatic updating through the Processing library manager over the next couple of days

**Comment by OpenSauce04** [comment]
Thanks for the reply!
