### ISSUE TITLE
Stutter and lag when playing multiple samples repeatedly

### ISSUE THREAD

**Issue by trackme518** [processing/processing-sound#74]
When using SoundFile class and triggering samples repeatedly it will start to stutter eventually. This is not happening in another audio library - Beads.  Also reported here: https://discourse.processing.org/t/sound-library-bugs-lagging-noise-choppy/4718 Example code below:

```
import processing.sound.*;

int timer;
SoundFile[] file = new SoundFile[5];

void setup() {
  size(640, 480);
  background(0);
  for (int i=0; i<file.length; i++) {
    file[i] = new SoundFile(this, "http://soundbible.com/grab.php?id=1705&type=wav" );
  }
  timer = millis();

  frameRate(30);
}


int numplays = 0;

void draw() {
  //around 800-1100 plays it will start to stutter
  if (numplays<1000) {
    if (millis() > timer + 20 ) {
      int i = (int)random(0, file.length);
      file[i].play();
      numplays++;
      println(numplays);
      timer = millis();
    }
  }
}
```

**Comment by kevinstadler** [comment]
Thanks for reporting! Presumably this is an issue with how extra JSyn data players are allocated ad hoc when a sound file that is already playing is cued to start another playback... This will require a bit of debugging around here to figure out whether the issue is with the JSyn engine being overloaded, or if it's a general garbage collection issue (in which case this TODO finally needs implementing...):

https://github.com/processing/processing-sound/blob/d508007ac1f7a5630d74a069307b70ad72333fcc/src/processing/sound/AudioSample.java#L305-L320

**Comment by trackme518** [comment]
Hi,
is it maybe possible to get number of used audio players at given time? So at least I could monitor it and restrict the max number....

**Comment by kevinstadler** [comment]
I had another look and it might not be just about the number of *active* audio players, but an issue of previously used but now inactive players staying connected to the synthesis engine forever. Could you do me a favour and try out the following test build and let me know if it improves the situation for you? [sound.zip](https://github.com/processing/processing-sound/files/10099126/sound.zip) Just extract it into your Processing's `libraries/` folder, replacing the `sound` directory that is already there.

I tried to test it with the sketch you posted above but I'm finding it difficult to hear past the clipping that's happening with too many simultaneous players, you probably have a better idea of what it should sound like...

(note that `audiosample.loop()` is probably not working in this build, all one-shot methods like `.play()`, `.jump()` etc should work as expected though)

**Comment by trackme518** [comment]
Hi,
I just tested the provided lib build, and the behavior seems unchanged.  Once the number of repeatedly played sounds exceeds the threshold, it will start to stutter even after the playback has finished.
