### ISSUE TITLE
Document amplitude range used internally (in AudioSample class?)

### ISSUE THREAD

**Issue by todocono** [processing/processing-sound#75]
I teach a class with Processing, and a colleague was surprised because the maximum amplitude she was getting from analyzing a microphone audio in was 0.5. 

For me these were not big news, but I remembered finding out this one or two years ago. Should the documentation be updated? Is it true for all computers? 

I have seen these results running on macOS 10.15.7, Processing 4.01, and the latest Sound library 2.3.1.

**Comment by kevinstadler** [comment]
The range of values of the samples should indeed be documented somewhere in the reference (at least for advanced users), thanks for reporting!
