### ISSUE TITLE
Suggestion for improving the way FFT works with sound files

### ISSUE THREAD

**Issue by damaru-inc** [processing/processing-sound#77]
I'm new to Processing and especially new to the sound library. I started playing with the FFT library. I want to be able to use an existing sound recording instead of live audio, and I was happy to see that I can pass a SoundFile to the FFT instance rather than an AudioIn as it shows in the example.

I want to be able to save the rendered frames using the saveFrame() function, and it works but there is a timing problem.

I've got it set up to do 30 frames per second, but it takes slightly more than 1/30 of a second to render the image. So it's only really saving 27-29 images per second. If I load the images and the sound file into a video editor, the timing is off.

I think that the solution would be to have a function in FFT that would take a fixed set of samples and analyze them, rather than having it follow audio in real time. So for each frame, assuming 30 fps, you extract 1/30 of a second worth of samples from the audio file, process them, render and save the frame. Then it won't matter how long it takes to render the frame.

Is this possible?

Thanks,
Michael Davis
Ottawa

**Comment by kevinstadler** [comment]
Hello Michael,

thanks that's an interesting problem. Specifying a fixed subset of the sample for FFT analysis is not currently possible with the library, but it would only take a small code change to add that functionality, which could be interesting to others as well. If you're happy to wait a few days I could probably come up with a test build which has that functionality built in?

Best

**Comment by damaru-inc** [comment]
Thanks for the fast response! I was going to try to do that myself if no one responded, but I started to study Fourier Analysis because I like to understand what I'm coding, but once they started to talk about integrals and imaginary numbers I realized I need to up my game on math first. Still I think I'll study this library. I am a Java programmer by profession.

I used Processing for my last project, for the first time. You can see it here in the synthesized snowflakes that appear around 3'30". http://music.damaru.com/TheSuchnessOfSnow.mp4

I'm very excited to see what I can do with the fft library for my next piece.

**Comment by kevinstadler** [comment]
Well in that case you should be able to make the necessary changes to the library yourself actually! Instructions on how to build the library can be found [here](https://github.com/processing/processing-sound#how-to-build), the only thing you need to have installed really is `ant`, or you can probably just build it from within your Java IDE of choice.

I would actually also not be able to implement FFT myself, the Sound library just uses JSyn's FFT implementation, which can take arbitrary samples and not just what is currently playing, just like what you are looking for. If you want to have a go at making the changes yourself, the low-level FFT analysis call is in this (non-public) internal FFT class, where you can see that it just copies the samples from the current playback position:
https://github.com/processing/processing-sound/blob/33b5ddf6fe7abe629c78aa3be0eea9a0f05f6fae/src/processing/sound/JSynFFT.java#L32-L45
What I could imagine is a new method `protected void calculateMagnitudesFromSample(float[] sample, float[] target)` which you can pass a raw `float[]` sample that you've extracted from a specific position of the file using [`audioSample.read()`](https://processing.org/reference/libraries/sound/AudioSample_read_.html).

You would also have to add a `public float[] analyzeSample(float[] sample)` to the `FFT` class which calls the `JSynFFT` method and exposes it to users, parallel to this one:
https://github.com/processing/processing-sound/blob/33b5ddf6fe7abe629c78aa3be0eea9a0f05f6fae/src/processing/sound/FFT.java#L79-L85

**Comment by damaru-inc** [comment]
I'll give it a shot, thanks for the code hints. I'm sure I'll have questions, should I ask them here or is there a better channel for discussion?

**Comment by kevinstadler** [comment]
For general usage questions there is the Processing Discourse at https://discourse.processing.org but since your questions are really related to the internals of the library it's probably more useful to keep them over here on Github!
