### ISSUE TITLE
APDE 

### ISSUE THREAD

**Issue by jafal633** [processing/processing-sound#90]
Hi 

Is this library compatible with APDE

Thanks I n advance

**Comment by kevinstadler** [comment]
Hello,

yes this library is fully compatible with Android and therefore also APDE. The only issue is that Android 5.1 and earlier are not supported (see #70), but if you have a reasonably new Android version everything should work. There's more information about download+installation on the APDE wiki: https://github.com/Calsign/APDE/wiki#how-do-i-install-a-library

**Comment by jafal633** [comment]
Hi Sir

Thank you
